# Generated by Django 2.0.6 on 2018-06-03 11:25

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(help_text="<a href='password/'>修改密码</a>", max_length=255, null=True, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('name', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='文章标题', max_length=32, verbose_name='文章标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='内容', verbose_name='内容')),
                ('add_date', models.DateTimeField()),
                ('read_times', models.IntegerField(default=0, help_text='所属系列', verbose_name='阅读次数')),
                ('update_date', models.DateTimeField(auto_now_add=True, help_text='最后修改时间', verbose_name='最后修改时间')),
                ('good', models.IntegerField(default=0, help_text='赞', verbose_name='赞')),
                ('bad', models.IntegerField(default=0, help_text='踩', verbose_name='踩')),
                ('auther', models.ForeignKey(default=1, help_text='作者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='ArticleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='系列文章', max_length=32, verbose_name='系列文章')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='说明', verbose_name='说明')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '文章系列',
                'verbose_name_plural': '文章系列',
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='标签名', max_length=32, unique=True, verbose_name='标签名')),
                ('details', models.TextField(help_text='说明', verbose_name='说明')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '文章标签',
                'verbose_name_plural': '文章标签',
            },
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='文章类型', max_length=32, verbose_name='文章类型')),
            ],
            options={
                'verbose_name': '文章类型',
                'verbose_name_plural': '文章类型',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter', models.CharField(blank=True, max_length=32, null=True)),
                ('reply_to', models.CharField(blank=True, max_length=32, null=True, verbose_name='回复对象')),
                ('content', models.TextField(verbose_name='留言内容')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='留言文章')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='blog.Comment', verbose_name='父回复')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': '访问者',
                'verbose_name_plural': '访问者',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='group',
            field=models.ForeignKey(blank=True, help_text='所属系列', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleGroup', verbose_name='所属系列'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', to='blog.ArticleTag'),
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.ForeignKey(blank=True, help_text='文章类型', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleType', verbose_name='文章类型'),
        ),
    ]
